### ISSUE TITLE
BRATS/HGG file is not found in dataset.ipynb

### ISSUE THREAD

**Issue by Ayushkumawat** [ShawkhIbneRashid/medical-images-sr#2] opened 2023-02-01 19:18 UTC
Getting FileNotFoundError for '/content/drive/My Drive/Colab Notebooks/BRATS/HGG' in dataset.ipynb file, there are some files missing in the directory, I don't know where to download them.
![image](https://user-images.githubusercontent.com/76219349/216140647-2b68147e-235b-46b7-91c3-a78ffd5660c2.png)

**Comment by ShawkhIbneRashid** [comment] 2023-02-02 19:12
I used the BRATS-2018 dataset. You can download the dataset and place it in a directory. After that specify the directory location in the data_path variable.

**Comment by Ayushkumawat** [comment] 2023-02-03 15:14
> I used the BRATS-2018 dataset. You can download the dataset and place it in a directory. After that specify the directory location in the data_path variable.

I am not able to find suitable data for the error I am getting, I've taken BRATS-2018 data from Kaggle but I am getting soo many errors while using it. Can you please provide the link to the dataset

**Comment by Ayushkumawat** [comment] 2023-02-03 15:16
> I used the BRATS-2018 dataset. You can download the dataset and place it in a directory. After that specify the directory location in the data_path variable.

I am not able to find suitable data for the error I am getting, I've taken BRATS-2018 data from Kaggle but I am getting soo many errors while using it. Can you please provide the link to the dataset

**Comment by ShawkhIbneRashid** [comment] 2023-02-03 16:04
> > I used the BRATS-2018 dataset. You can download the dataset and place it in a directory. After that specify the directory location in the data_path variable.
> 
> I am not able to find suitable data for the error I am getting, I've taken BRATS-2018 data from Kaggle but I am getting soo many errors while using it. Can you please provide the link to the dataset

Can you post a screenshot of the errors that you are getting now?

**Comment by Ayushkumawat** [comment] 2023-02-03 17:37
![image](https://user-images.githubusercontent.com/76219349/216668408-0a4ae735-d6e3-451c-bf30-c1c96203ce0c.png)

I am getting this above error, While I am running this code from dataset.ipynb

#saves the HR and LR images in numpy format from nift format to be used for testing and training Real-ESRGAN and ESRGAN
#specify the location to save the HR and LR images
dim = (64,64)
count_neg = 0
a_ssim = []
start = 0
end = 223
count = 0
count_blank = 0

for i in range(start,end):
  data = data_loader(i)
  data = data.astype('float32')
  print(data.shape)
  for j,img in enumerate(data):
    count+=1
    max = np.max(img)
    min = np.min(img)
    if max != min:
      count_blank+=1
      img = (img-np.min(img))/(np.max(img)-np.min(img))
      a = int((256-img.shape[0])/2)
      b = int((256-img.shape[1])/2)
      if a<0 or b<0:
        count_neg+=1
        continue
      img = np.pad(img, [(a, a), (b, b)], mode='constant')
      #img = np.rot90(img)
      img = img[:,:,np.newaxis]
      np.save(str(i) + "_slc" + str(j)  + "_org.npy", img)

      slce_ds = getLR(img)
      slce_ds = cv2.resize(slce_ds, dim, interpolation=cv2.INTER_LINEAR)
      slce_ds = replace_value(slce_ds, img)
      slce_ds =(slce_ds-np.min(slce_ds))/(np.max(slce_ds)-np.min(slce_ds))
      np.save(str(i) + "_slc" + str(j)  + "_lr.npy", slce_ds)

**Comment by ShawkhIbneRashid** [comment] 2023-02-03 19:14
The issue is in the yellow marked area. Put a / after HGG 
![image](https://user-images.githubusercontent.com/38233390/216687751-17420f0e-d3ef-4868-8033-4f0364be93ad.png)

**Comment by Ayushkumawat** [comment] 2023-02-03 19:27
![image](https://user-images.githubusercontent.com/76219349/216689913-7b5d35c9-d102-4ffc-87da-881531e19f96.png)

Getting this new error, I think this is because my dataset has only 20 directories and the range is getting 223 iterations 

![image](https://user-images.githubusercontent.com/76219349/216690443-573b3678-b183-4a6a-bd27-0b4160a2b7da.png)

**Comment by ShawkhIbneRashid** [comment] 2023-02-03 19:36
Yes, that is the reason for this error. As your initial problem is resolved, I am closing this issue. Please open a new issue if you face any other problems.

**Comment by ShawkhIbneRashid** [comment] 2023-02-03 19:37
Yes, that is the reason for this error. As your initial problem is resolved, I am closing this issue. Please open a new issue if you face any other problems.

**Closed as completed by ShawkhIbneRashid** 2023-02-03 19:37 UTC
